In [ ]:
import pandas as pd

#Series

In [ ]:
a = 200
b=500
c=400
data = [a,b,c]

series = pd.Series(data)
print(series)

0    200
1    500
2    400
dtype: int64

In [ ]:
data = ['a','b','c']

series = pd.Series(data)
print(series)

0    a
1    b
2    c
dtype: object

In [ ]:
data = [True,False]

series = pd.Series(data)
print(series)

0     True
1    False
dtype: bool

In [ ]:
a = 200
b=500
c=400
data = [a,b,c]

series = pd.Series(data, index=['a','b','c'])
print(series)

a    200
b    500
c    400
dtype: int64

In [ ]:
a = 200
b=500
c=400
data = [a,b,c]

series = pd.Series(data, index=['flore','flore','flore'])
print(series)

flore    200
flore    500
flore    400
dtype: int64

In [ ]:
a = 200
b=500
c=400
data = [a,b,c]

series = pd.Series(data, index=['a','b','c'])
print(series.loc["a"])



a = 200
b=500
c=400
data = [a,b,c]

series = pd.Series(data, index=['a','b','c'])
print(series.loc["b"])

200
500

In [ ]:

a = 200
b=500
c=400
data = [a,b,c]

series = pd.Series(data, index=['a','b','c'])
series.loc["c"] =200
print(series)

a    200
b    500
c    200
dtype: int64

In [ ]:
import pandas as pd

series = pd.Series([200, 500, 400, 700, 450], index=['a', 'b', 'c','d','e'])

print(series[series >=300])

b    500
c    400
d    700
e    450
dtype: int64

In [ ]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)
print(myvar["day1"])
print(myvar["day2"])
print(myvar["day3"])

day1    420
day2    380
day3    390
dtype: int64
420
380
390

In [ ]:
myvar.loc["day3"] += 3200

In [ ]:
print(myvar["day3"])

3590

In [ ]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)
print(myvar[myvar>=300])

day1    420
day2    380
day3    390
dtype: int64

#DataFrame

In [ ]:
data = {
    "Name" : ["harshit","babu","chotu"],
    "Age" : [30,39,24],
    "Salary":[10000,20000,30000]
}

df = pd.DataFrame(data)
print(df)

df = pd.DataFrame(data, index= ["EP1","EP2","EP3"])
print(df.loc["EP2"])

      Name  Age  Salary
0  harshit   30   10000
1     babu   39   20000
2    chotu   24   30000
Name       babu
Age          39
Salary    20000
Name: EP2, dtype: object

In [ ]:
print(df.iloc[1])

Name       babu
Age          39
Salary    20000
Name: EP2, dtype: object

In [ ]:
print(df)

        Name  Age  Salary
EP1  harshit   30   10000
EP2     babu   39   20000
EP3    chotu   24   30000

add a new colum

In [ ]:
df["job"]= ["cook","waterboy", "n/a"]

add new column

In [ ]:
new_row = pd.DataFrame([{"Name":"Sandy","Age":28,"job":"Engineer"},
                        {"Name":"alex","Age":28,"job":"Docter"}],
                       index=["EP4","EP5"])
df = pd.concat([df, new_row])

In [ ]:
print(df)

        Name  Age   Salary       job
EP1  harshit   30  10000.0      cook
EP2     babu   39  20000.0  waterboy
EP3    chotu   24  30000.0       n/a
0      Sandy   28      NaN  Engineer
EP4    Sandy   28      NaN  Engineer
EP4    Sandy   28      NaN  Engineer
EP4    Sandy   28      NaN  Engineer
EP4    Sandy   28      NaN  Engineer
EP5     alex   28      NaN    Docter
EP4    Sandy   28      NaN  Engineer
EP5     alex   28      NaN    Docter

#Importing CSV & JSON

ai_student_impact_dataset (1)

In [ ]:
df_csv = pd.read_csv('ai_student_impact_dataset (1).csv')
display(df_csv.head())

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [ ]:
print(df_csv.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  object
 2   Year_of_Study               50000 non-null  object
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  object
 6   Prompt_Engineering_Skill    50000 non-null  object
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  bool
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  object
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  object
dtypes: bool(1), float64(5), int64(4), object(6)
memory usage: 5.8+ MB
None

In [ ]:
print(df_csv.to_string())

Output hidden; open in https://colab.research.google.com to view.

#Selection

In [92]:
print(df_csv['Student_ID'])

0        100001
1        100002
2        100003
3        100004
4        100005
          ...
49995    149996
49996    149997
49997    149998
49998    149999
49999    150000
Name: Student_ID, Length: 50000, dtype: int64

In [98]:
import pandas as pd

df = pd.read_csv("ai_student_impact_dataset (1).csv")

In [99]:
df["Major_Category"]

0        Humanities
1           Medical
2          Business
3          Business
4              STEM
            ...
49995      Business
49996          STEM
49997      Business
49998      Business
49999          Arts
Name: Major_Category, Length: 50000, dtype: object

In [100]:
df[["Student_ID", "Major_Category", "Post_Semester_GPA"]]

       Student_ID Major_Category  Post_Semester_GPA
0          100001     Humanities              2.393
1          100002        Medical              3.696
2          100003       Business              3.499
3          100004       Business              4.000
4          100005           STEM              3.798
...           ...            ...                ...
49995      149996       Business              3.584
49996      149997           STEM              3.096
49997      149998       Business              3.605
49998      149999       Business              3.527
49999      150000           Arts              3.261

[50000 rows x 3 columns]

In [101]:
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [102]:
df.tail()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [103]:
df.iloc[0:5]

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [104]:
df.iloc[5:10, 0:3]

   Student_ID Major_Category Year_of_Study
5      100006           STEM        Junior
6      100007           STEM      Freshman
7      100008           Arts        Junior
8      100009       Business     Sophomore
9      100010       Business     Sophomore

In [105]:
df.loc[0]

Student_ID                                   100001
Major_Category                           Humanities
Year_of_Study                                Senior
Pre_Semester_GPA                              2.418
Weekly_GenAI_Hours                            23.31
Primary_Use_Case               Copywriting/Drafting
Prompt_Engineering_Skill                   Beginner
Tool_Diversity                                    1
Paid_Subscription                              True
Traditional_Study_Hours                        8.13
Perceived_AI_Dependency                           5
Institutional_Policy          Allowed_With_Citation
Anxiety_Level_During_Exams                        6
Post_Semester_GPA                             2.393
Skill_Retention_Score                         86.44
Burnout_Risk_Level                             High
Name: 0, dtype: object

In [106]:
df.loc[0:5, ["Major_Category", "Post_Semester_GPA"]]

  Major_Category  Post_Semester_GPA
0     Humanities              2.393
1        Medical              3.696
2       Business              3.499
3       Business              4.000
4           STEM              3.798
5           STEM              3.666

2. Filtering
Students with GPA greater than 3

In [107]:
df[df["Post_Semester_GPA"] > 3]

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
5,100006,STEM,Junior,3.449,6.50,Debugging/Troubleshooting,Beginner,1,False,14.19,4,Allowed_With_Citation,5,3.666,65.92,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [108]:
df[df["Major_Category"] == "STEM"]

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
5,100006,STEM,Junior,3.449,6.50,Debugging/Troubleshooting,Beginner,1,False,14.19,4,Allowed_With_Citation,5,3.666,65.92,High
6,100007,STEM,Freshman,3.622,31.41,Summarizing_Reading,Advanced,5,True,13.11,8,Allowed_With_Citation,7,4.000,67.97,Medium
10,100011,STEM,Graduate,3.407,5.16,Summarizing_Reading,Advanced,3,False,11.43,5,Allowed_With_Citation,3,3.617,95.42,High
13,100014,STEM,Junior,3.225,8.95,Direct_Answer_Generation,Beginner,1,False,25.30,2,Allowed_With_Citation,3,3.935,64.47,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49980,149981,STEM,Graduate,3.419,25.47,Summarizing_Reading,Advanced,4,True,14.24,6,Allowed_With_Citation,7,3.879,66.16,High
49981,149982,STEM,Graduate,2.256,10.89,Copywriting/Drafting,Advanced,4,False,10.42,1,Allowed_With_Citation,1,2.450,84.88,Low
49988,149989,STEM,Sophomore,2.058,3.32,Debugging/Troubleshooting,Beginner,1,False,6.34,4,Actively_Encouraged,4,2.147,68.75,Low
49993,149994,STEM,Sophomore,3.588,25.64,Debugging/Troubleshooting,Intermediate,3,True,4.62,5,Strict_Ban,10,3.841,58.44,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium

In [109]:
df[df["Paid_Subscription"] == "Yes"]

Empty DataFrame
Columns: [Student_ID, Major_Category, Year_of_Study, Pre_Semester_GPA, Weekly_GenAI_Hours, Primary_Use_Case, Prompt_Engineering_Skill, Tool_Diversity, Paid_Subscription, Traditional_Study_Hours, Perceived_AI_Dependency, Institutional_Policy, Anxiety_Level_During_Exams, Post_Semester_GPA, Skill_Retention_Score, Burnout_Risk_Level]
Index: []

In [110]:
df[(df["Major_Category"] == "STEM") &
   (df["Post_Semester_GPA"] > 3)]

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
5,100006,STEM,Junior,3.449,6.50,Debugging/Troubleshooting,Beginner,1,False,14.19,4,Allowed_With_Citation,5,3.666,65.92,High
6,100007,STEM,Freshman,3.622,31.41,Summarizing_Reading,Advanced,5,True,13.11,8,Allowed_With_Citation,7,4.000,67.97,Medium
10,100011,STEM,Graduate,3.407,5.16,Summarizing_Reading,Advanced,3,False,11.43,5,Allowed_With_Citation,3,3.617,95.42,High
13,100014,STEM,Junior,3.225,8.95,Direct_Answer_Generation,Beginner,1,False,25.30,2,Allowed_With_Citation,3,3.935,64.47,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49973,149974,STEM,Graduate,3.317,10.11,Summarizing_Reading,Advanced,4,True,8.04,3,Strict_Ban,7,3.578,75.39,Medium
49974,149975,STEM,Junior,3.087,1.55,Copywriting/Drafting,Beginner,2,False,1.00,1,Strict_Ban,4,3.350,60.83,Medium
49980,149981,STEM,Graduate,3.419,25.47,Summarizing_Reading,Advanced,4,True,14.24,6,Allowed_With_Citation,7,3.879,66.16,High
49993,149994,STEM,Sophomore,3.588,25.64,Debugging/Troubleshooting,Intermediate,3,True,4.62,5,Strict_Ban,10,3.841,58.44,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium

In [111]:
df[df["Major_Category"].isin(["Business", "Medical"])]

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
8,100009,Business,Sophomore,3.420,2.00,Debugging/Troubleshooting,Beginner,2,True,2.87,1,Strict_Ban,5,3.396,55.71,Medium
9,100010,Business,Sophomore,3.046,19.99,Debugging/Troubleshooting,Intermediate,2,True,12.49,3,Strict_Ban,8,2.978,87.18,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49990,149991,Business,Senior,2.970,2.63,Summarizing_Reading,Intermediate,2,False,24.95,1,Allowed_With_Citation,1,3.238,84.87,Medium
49992,149993,Business,Graduate,2.829,2.59,Debugging/Troubleshooting,Advanced,3,True,7.54,1,Allowed_With_Citation,4,3.176,84.04,Low
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium

In [112]:
df[df["Paid_Subscription"] != "Yes"]

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

3. Aggregation
Mean GPA

In [113]:
df["Post_Semester_GPA"].mean()

np.float64(3.34929942)

In [114]:
df["Post_Semester_GPA"].max()

4.0

In [115]:
df["Weekly_GenAI_Hours"].sum()

np.float64(421387.61)

In [116]:
df.groupby("Major_Category")["Post_Semester_GPA"].mean()

Major_Category
Arts          3.343688
Business      3.336085
Humanities    3.345825
Medical       3.353168
STEM          3.363154
Name: Post_Semester_GPA, dtype: float64

In [117]:
df.groupby("Major_Category")["Weekly_GenAI_Hours"].mean()

Major_Category
Arts           7.271702
Business       8.275898
Humanities     6.770144
Medical        7.546728
STEM          10.488609
Name: Weekly_GenAI_Hours, dtype: float64

In [118]:
df.groupby("Major_Category").agg({
    "Post_Semester_GPA":"mean",
    "Weekly_GenAI_Hours":"sum",
    "Skill_Retention_Score":"max"
})

                Post_Semester_GPA  Weekly_GenAI_Hours  Skill_Retention_Score
Major_Category
Arts                     3.343688            43143.01                  100.0
Business                 3.336085           103763.21                  100.0
Humanities               3.345825            67660.82                  100.0
Medical                  3.353168            48872.61                  100.0
STEM                     3.363154           157947.96                  100.0

In [119]:
df.isnull()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [120]:
df.isnull().sum()

Student_ID                    0
Major_Category                0
Year_of_Study                 0
Pre_Semester_GPA              0
Weekly_GenAI_Hours            0
Primary_Use_Case              0
Prompt_Engineering_Skill      0
Tool_Diversity                0
Paid_Subscription             0
Traditional_Study_Hours       0
Perceived_AI_Dependency       0
Institutional_Policy          0
Anxiety_Level_During_Exams    0
Post_Semester_GPA             0
Skill_Retention_Score         0
Burnout_Risk_Level            0
dtype: int64

In [121]:
df.dropna()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [122]:
df.dropna()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [123]:
df.fillna(0)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [124]:
df["Post_Semester_GPA"].fillna(df["Post_Semester_GPA"].mean())

0        2.393
1        3.696
2        3.499
3        4.000
4        3.798
         ...
49995    3.584
49996    3.096
49997    3.605
49998    3.527
49999    3.261
Name: Post_Semester_GPA, Length: 50000, dtype: float64

In [125]:
df.drop_duplicates()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [126]:
df.duplicated().sum()

np.int64(0)

In [127]:
df.rename(columns={
    "Post_Semester_GPA":"Final_GPA"
})

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Final_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [132]:
year_mapping = {
    'Freshman': 1,
    'Sophomore': 2,
    'Junior': 3,
    'Senior': 4,
    'Graduate': 5
}
df["Year_of_Study"] = df["Year_of_Study"].replace(year_mapping).astype(int)

/tmp/ipykernel_20021/3293639108.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Year_of_Study"] = df["Year_of_Study"].replace(year_mapping).astype(int)

In [129]:
df["Paid_Subscription"] = df["Paid_Subscription"].replace({
    "Yes":"Subscribed",
    "No":"Not Subscribed"
})

In [130]:
df.sort_values("Post_Semester_GPA", ascending=False)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
49979,149980,Business,Senior,3.750,16.00,Ideation,Beginner,1,True,7.00,3,Allowed_With_Citation,1,4.000,66.12,Low
49976,149977,Business,Graduate,3.692,7.31,Summarizing_Reading,Beginner,3,False,18.38,5,Actively_Encouraged,5,4.000,66.81,Medium
29,100030,STEM,Sophomore,3.638,12.83,Debugging/Troubleshooting,Advanced,4,True,10.25,5,Allowed_With_Citation,4,4.000,61.29,Medium
25,100026,Arts,Senior,3.308,2.38,Ideation,Advanced,4,True,11.33,2,Actively_Encouraged,2,4.000,81.85,High
49950,149951,Humanities,Freshman,3.848,3.64,Copywriting/Drafting,Intermediate,4,False,12.23,1,Allowed_With_Citation,4,4.000,79.59,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11360,111361,Arts,Freshman,1.408,1.58,Direct_Answer_Generation,Intermediate,2,False,4.42,2,Actively_Encouraged,5,1.316,68.63,Low
39393,139394,Medical,Junior,1.703,24.47,Direct_Answer_Generation,Beginner,3,False,3.33,4,Allowed_With_Citation,6,1.226,53.30,High
10884,110885,Business,Freshman,1.183,12.83,Summarizing_Reading,Beginner,3,False,13.21,5,Allowed_With_Citation,8,1.209,81.87,High
43351,143352,Humanities,Junior,1.346,7.22,Copywriting/Drafting,Beginner,1,False,2.18,2,Strict_Ban,3,1.190,59.03,Medium
18078,118079,STEM,Junior,1.431,40.00,Direct_Answer_Generation,Beginner,1,True,8.95,9,Strict_Ban,9,1.000,10.78,High

In [131]:
df.sort_values("Weekly_GenAI_Hours")

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
23628,123629,Humanities,Junior,1.543,0.0,Direct_Answer_Generation,Beginner,3,False,9.63,2,Allowed_With_Citation,2,1.740,74.13,Medium
11590,111591,Humanities,Sophomore,3.529,0.0,Copywriting/Drafting,Beginner,3,True,7.59,4,Allowed_With_Citation,4,3.569,77.12,Low
39443,139444,Humanities,Junior,3.338,0.0,Copywriting/Drafting,Intermediate,3,True,1.80,2,Allowed_With_Citation,4,3.288,59.00,Low
5360,105361,Business,Sophomore,3.008,0.0,Ideation,Beginner,2,True,18.58,2,Allowed_With_Citation,5,3.636,60.87,Low
34516,134517,Business,Junior,3.630,0.0,Ideation,Intermediate,2,False,12.09,1,Allowed_With_Citation,6,3.754,63.11,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8502,108503,STEM,Sophomore,3.047,40.0,Direct_Answer_Generation,Intermediate,1,True,12.19,7,Allowed_With_Citation,5,2.633,67.04,High
15933,115934,STEM,Junior,2.739,40.0,Debugging/Troubleshooting,Advanced,3,True,15.81,10,Strict_Ban,10,3.424,63.81,High
42300,142301,Business,Junior,2.698,40.0,Direct_Answer_Generation,Advanced,3,False,18.75,10,Allowed_With_Citation,8,2.114,55.88,High
49937,149938,Business,Freshman,3.113,40.0,Direct_Answer_Generation,Intermediate,2,True,14.87,9,Allowed_With_Citation,7,2.875,23.86,High
36328,136329,Business,Sophomore,2.251,40.0,Ideation,Advanced,4,True,9.20,8,Allowed_With_Citation,3,2.824,76.38,High